USE DATABASE EVENT_STREAMING;
USE SCHEMA STAGE;

CREATE TABLE IF NOT EXISTS THREADMATRIX_EVENTS (
    EVENT_ID STRING,
    CASE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    EVENT_TYPE STRING,
    PRIORITY STRING,
    STATUS STRING,
    ASSIGNED_TO STRING,
    EVENT_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_SYSTEM STRING,
    LOAD_TIME TIMESTAMP_NTZ
);