USE DATABASE EVENT_STREAMING;
USE SCHEMA STAGE;

INSERT INTO THREADMATRIX_EVENTS (
    EVENT_ID,
    CASE_ID,
    CUSTOMER_ID,
    EVENT_TYPE,
    PRIORITY,
    STATUS,
    ASSIGNED_TO,
    EVENT_TIMESTAMP,
    SOURCE_SYSTEM,
    LOAD_TIME
)
SELECT
    RAW_DATA:event_id::STRING,
    RAW_DATA:case_id::NUMBER,
    RAW_DATA:customer_id::NUMBER,
    RAW_DATA:event_type::STRING,
    RAW_DATA:priority::STRING,
    RAW_DATA:status::STRING,
    RAW_DATA:assigned_to::STRING,
    RAW_DATA:event_timestamp::TIMESTAMP_NTZ,
    SOURCE_SYSTEM,
    LOAD_TIME
FROM EVENT_STREAMING.RAW.THREADMATRIX_EVENTS_RAW;