USE DATABASE EVENT_STREAMING;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS THREADMATRIX_EVENTS_RAW (
    FILE_NAME STRING,
    LOAD_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM STRING,
    RAW_DATA VARIANT
);